// <auto-generated />
using LeaveManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeaveManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    [Migration("20230317035608_connectDB")]
    partial class connectDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeaveManagementSystem.Models.LoginModel", b =>
                {
                    b.Property<string>("EmployeeUsername")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Employeeconfirmpassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employeepassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("managerusername")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeUsername");

                    b.ToTable("Login");
                });
#pragma warning restore 612, 618
        }
    }
}
